services:
  app:
    container_name: table_reserve_app
    build: ./
    depends_on:
      - postgres
    volumes:
      - ./:/src
    ports:
      - 8000:8000
    restart: always
    env_file:
      - .env
  postgres:
    container_name: table_reserve_db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT}:5432"
    restart: always

volumes:
  pgdata:
    driver: local
